apiVersion: v2
appVersion: "1.0"
description: A Helm chart for response api
name: rpe-response-api
home: https://github.com/hmcts/incident-response-api
version: 1.0.7
dependencies:
  - name: nodejs
    version: 2.4.17
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: job
    version: 1.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
