nodejs:
  applicationPort: 3100
  ingressHost: response-api.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/rpe/response-api:db48cb'
  secrets: 
    SLACK_TOKEN:
        secretRef: response
        key: SLACK_TOKEN
    SLACK_SIGNING_SECRET:
        secretRef: response
        key: SLACK_SIGNING_SECRET
    DB_PASSWORD:
        secretRef: response
        key: DB_PASSWORD
  environment:
    SITE_URL: https://response.platform.hmcts.net
    INCIDENT_BOT_NAME: incident_response
    INCIDENT_CHANNEL_NAME: incidents
    INCIDENT_REPORT_CHANNEL_NAME: incidents
    DB_USER: response@hmcts-incident-response
    DB_NAME: response
job:
  image: hmctspublic.azurecr.io/curl:alpine-bash
  schedule: "*/1 * * * *"
  args:
    - -v
    - http://response-api-nodejs/slack/cron_minute