nodejs:
  applicationPort: 8000
  ingressHost: response-api.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/rpe/response-api:latest'
  secrets: 
    SLACK_TOKEN:
        secretRef: response
        key: SLACK_TOKEN
    SLACK_SIGNING_SECRET:
        secretRef: response
        key: SLACK_SIGNING_SECRET
    DB_PASSWORD:
        secretRef: response
        key: DB_PASSWORD
  environment:
    SITE_URL: https://response.platform.hmcts.net
    INCIDENT_BOT_NAME: inc_response_hmcts
    INCIDENT_CHANNEL_NAME: incidents
    INCIDENT_REPORT_CHANNEL_NAME: incidents
    INCIDENT_BOT_ID: U013Y4HJEF8
    DB_USER: response
    DB_NAME: response
    POSTGRES: true
    DB_HOST: hmcts-incident-response-flexible-ptl.postgres.database.azure.com
    DB_SSL_MODE: require
job:
  image: hmctspublic.azurecr.io/curl:7.70.0
  schedule: "*/1 * * * *"
  kind: CronJob
  args:
    - -v
    - http://rpe-response-api-nodejs/slack/cron_minute
